openapi: 3.0.3
info:
  title: "UECS Navi API"
  version: "1.0.0"
paths:
  /climate-datas:
    get:
      operationId: getClimateData
      tags:
        - private
      summary: Get climate data list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClimateDatasResponse"
  /houses:
    get:
      operationId: getHouses
      tags:
        - private
      summary: Get houses list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HousesResponse"
    post:
      operationId: createHouse
      tags:
        - private
      summary: Create a house
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HousesRequest"
      responses:
        "200":
          description: OK

  /houses/{house-id}:
    parameters:
      - $ref: "#/components/parameters/house-id"
    get:
      operationId: getDevice
      tags:
        - private
      summary: Get devices list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeviceResponse"

  /houses/{house-id}/devices:
    parameters:
      - $ref: "#/components/parameters/house-id"
    post:
      operationId: createDevice
      tags:
        - private
      summary: Create device
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRequest"
      responses:
        "200":
          description: OK

  /workflows-with-ui:
    get:
      operationId: getWorkflowsWithUI
      tags:
        - private
      summary: Get workflows with ui
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkflowWithUIResponse"

    post:
      operationId: createWorkflowWithUI
      tags:
        - private
      summary: Create a workflow with UI
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkflowWithUIRequest"
      responses:
        "200":
          description: OK


  /workflows:
    get:
        operationId: getWorkflows
        tags:
          - private
        summary: Get workflows list
        responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/WorkflowResponse"
    post:
      operationId: createWorkflow
      tags:
        - private
      summary: Create a workflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkflowRequest"
      responses:
        "200":
          description: OK

  /time-schedule:
    post:
      operationId: createAndBuildTimeSchedule
      tags:
      - private
      summary: Create and build time schedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TimeScheduleRequest"

components:
  parameters:
    house-id:
      name: house-id
      in: path
      required: true
      schema:
        type: integer
    m304-id:
      name: m304-id
      in: path
      required: true
      schema:
        type: integer

  schemas:
    # Requests
    HousesRequest:
      type: string

    DeviceRequest:
      type: object
      properties:
        device_name:
          type: string
        climate_data_id:
          type: integer
        unit:
          type: string
        set_point:
          type: number
          format: double
        duration:
          type: integer
          nullable: true

    NodeRequest: 
      type: object
      properties:
        workflow_id:
          type: integer
        workflow_node_id:
          type: string
        type: 
          type: string
        data: 
          type: object
          additionalProperties: true
        position_x:
          type: number
          format: float
        position_y:
          type: number
          format: float

    EdgeRequest:
      type: object
      properties:
        workflow_id:
          type: integer
        source_node_id:
          type: string
        target_node_id:
          type: string

    WorkflowUIRequest:
          type: object
          properties:
            nodes: 
              type: array
              items:
                $ref: "#/components/schemas/NodeRequest"
            edges:
              type: array
              items:
                $ref: "#/components/schemas/EdgeRequest"

    WorkflowRequest:
      type: string

    WorkflowWithUIRequest:
      type: object
      properties:
        workflow:
          $ref: "#/components/schemas/WorkflowRequest"
        workflowUI:
          $ref: "#/components/schemas/WorkflowUIRequest"

    TimeSchedule:
      type: object
      properties:
        start_time:
          type: string
          pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]$"
          description: "開始時刻（HH:mm形式）"
        end_time:
          type: string
          pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]$"
          description: "終了時刻（HH:mm形式）"
        workflows:
          type: array
          items: 
            $ref: "#/components/schemas/WorkflowRequest"

    TimeScheduleRequest:
      type: array
      items: 
        $ref: "#/components/schemas/TimeSchedule"

    # Responses
    ClimateDatasResponse:
      type: object
      properties:
        id:
          type: integer
        climate_data:
          type: string
        unit:
          type: string
    HousesResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    DeviceResponse:
      type: object
      properties:
        id:
          type: integer
        device_name:
          type: string
        climate_data:
          type: string
        unit:
          type: string
        set_point:
          type: number
          format: double
        duration:
          type: integer

    WorkflowResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    NodeResponse: 
      type: object
      properties:
        id:
          type: integer
        workflow_id:
          type: integer
        workflow_node_id:
          type: string
        type: 
          type: string
        data: 
          type: object
          additionalProperties: true
        position_x:
          type: number
          format: float
        position_y:
          type: number
          format: float

    EdgeResponse:
      type: object
      properties:
        id:
          type: integer
        workflow_id:
          type: integer
        source_node_id:
          type: string
        target_node_id:
          type: string
          
    WorkflowUIResponse:
          type: object
          properties:
            nodes: 
              type: array
              items:
                $ref: "#/components/schemas/NodeResponse"
            edges:
              type: array
              items:
                $ref: "#/components/schemas/EdgeResponse"

    WorkflowWithUIResponse:
      type: object
      properties:
        workflow:
          $ref: "#/components/schemas/WorkflowResponse"
        workflowUI:
          $ref: "#/components/schemas/WorkflowUIResponse"

